[package]
name = "keez"
version = "0.1.0"
authors = ["Paul <paul@ravi>"]
edition = "2018"

[dependencies]
rusoto_core = "0.45.0"
rusoto_ssm = "0.45.0"
structopt = "0.3.17"

[patch.crates-io]
pkg-config = { git = "https://github.com/Litarvan/pkg-config-rs" }
